import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class ActivityCreate {
  @ApiProperty()
  name: string;
  @ApiProperty()
  description: string;
}

export class Activity {
  @ApiProperty()
  id: number;
  @ApiProperty()
  name: string;
  @ApiProperty()
  description: string;
}
